### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by proximityblue** [Brionjv/Miitopia-Save-Editor#12]
Hi, I recently downloaded this save editor again recently. I backed up my Miitopia save file using Checkpoint, and loaded it into the editor. I did all the gold, tickets, armour and weapons and restored it back in my 3DS. However, it does not load up..why is that? I set the region right (I'm EU)
:(

I just really want this to work as i love that game

**Comment by Brionjv** [comment]
Hi, 
are you restore your entire save file folder ? if you restore only on file your save file will be deleted when you load the game.

**Comment by proximityblue** [comment]
so you're saying i have to edit all my .sav files? will that work?

**Comment by Brionjv** [comment]
No, just edit file you want and restore all of them.
You must restore your entire save file folder (with common.sav, cottage.sav, event_flag, hero.sav, map_flag, quest.sav, stage_flag)
