### ISSUE TITLE
Will you make a version for the Switch?

### ISSUE THREAD

**Issue by NinjaNugget64** [Brionjv/Miitopia-Save-Editor#13]
Im just wondering for when the new Switch port comes out, if you will make a version for the save editor for the Switch.

**Comment by Brionjv** [comment]
If I have time yes

**Comment by NinjaNugget64** [comment]
> If I have time yes

Alright. There will be more content added to it such as a horse as an ally and makeup/wigs. There will be more content i think, but i am not too sure yet, I will probably pre-order it and maybe tell you about the game and which things could be added to the save editor and such.

**Comment by NinjaNugget64** [comment]
Hello! I just played the demo!
There seems to be one big save file instead of a bunch of smaller ones, so i guess the making of the editor would be harder?
Well, that was what i heard at least!
I think they are also adding more costumes, plus they are adding tickets you can use for 2 Miis to go out to better their relationship.

Im not too sure what "to do" means, but i assume it means you'll do it? If not, can you explain what it means?

**Comment by Brionjv** [comment]
Hi,
I don't know, I'll see. I already found some things
I started to create a save editor, for now it's possible to edit gold, hp banana and mp candy

**Comment by NinjaNugget64** [comment]
Alright. There might be more added in the future so we must look out for the full game.

**Comment by Brionjv** [comment]
Here Switch version : https://github.com/Brionjv/Miitopia-Save-Editor-Switch-Version

**Comment by NinjaNugget64** [comment]
Looking nice! Ill look forward for updates! (if you update the editor at all-)
