### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Myselforsomethingsimilar** [Brionjv/Miitopia-Save-Editor#18]
Whenever I save and copy and paste the file where I saved my new changes, the changes don't appear, the save data isn't corrupted but the changes are not there and all the values stay the same. I'm sure I save every time though. 

Edit. I tried keeping the bak > hero/common folder open when i was editing and saving, but the file inside of the new folder had the date and hour of the last moment I saved in-game, which rarely corresponds to the one I edited the file.

**Comment by Brionjv** [comment]
Files in bak folder is only in case something goes wrong, save editor make a backup before any changes.
Edit your save file directly on your SD card.
