### ISSUE TITLE
one food is missing

### ISSUE THREAD

**Issue by Sparky7198** [Brionjv/Miitopia-Save-Editor#2]
you forgot to make a code for this food: https://cdn.discordapp.com/attachments/249668118660644865/342445439661899776/image.jpg

**Comment by Brionjv** [comment]
which version are you tried ? an version on Github or gbatemp.net ? if it's on gbatemp.net : some foods are missing, it's will be fix on next update

**Comment by Sparky7198** [comment]
i used gbatemp.net to get here. so i assume im using the github version (if not can you link me to it?)

**Comment by Kyusetzu** [comment]
The gbatemp.net version is from [Here](https://github.com/Brionjv/Miitopia-Save-Editor/releases)
The Github version is directly from [Here](https://github.com/Brionjv/Miitopia-Save-Editor)

**Comment by Sparky7198** [comment]
thanks.
