### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Erc333** [Brionjv/Miitopia-Save-Editor#3]
I noticed that while the game did just come out in the west, the editor is still very limited. Is there a plan to add an inventory editor for each mii in the future? I got the editor specifically for that reason. Cheers and thanks for reading this!

**Comment by Brionjv** [comment]
Yes, if it's possible, some things come on next updates, it's a little limited now but after there will be more features

**Comment by Erc333** [comment]
k thanks for actually responding! I'll keep an eye out on youtube and here for more info on the editor!
