### ISSUE TITLE
multiple errors

### ISSUE THREAD

**Issue by myrrien** [Brionjv/Miitopia-Save-Editor#6]
everytime I try to unlock all amiibo costumes the save editor crashes
everytime I try to save my common.sav the editor writes 'an error has occurred' and crashes
using EU save in Italian language

**Comment by Brionjv** [comment]
Make sure you have load a save file, can you sent your save file to see what goes wrong ?

**Comment by myrrien** [comment]
I managed to get it to work, seems likely that it didn't like my SD card or
the path containing an @

Il 01 Set 2017 19:16, "Brionjv" <notifications@github.com> ha scritto:

**Comment by Brionjv** [comment]
ok, it's work
