### ISSUE TITLE
Edit mii level?

### ISSUE THREAD

**Issue by ghost** [Brionjv/Miitopia-Save-Editor#7]
i upload Miitopia in yt
I always lose
everyone says why you level up your mii to level 50?
I get a lot of dislikes

**Comment by Kyusetzu** [comment]
Thats your own fault.
Go to Level by Class and click on the version on the bottom left.
Then try to experiment with the EXP numbers.

**Comment by ghost** [comment]
SAVE CORRUPTED

**Comment by ghost** [comment]
DELETED!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ghost** [comment]
DONT WORKS WITH BACKUP

**Comment by Brionjv** [comment]
make sure you have restore all files

**Comment by ghost** [comment]
used backup from SE, i only edited hero.sav

**Comment by Brionjv** [comment]
If you edit hero.sav, you need to restore all files in save file folder, common.sav, hero.sav, quest.sav, cottage.sav, event_flag, map_flag, stage_flag. If one file is missing your save will be deleted by the game.
Make sure you have use right version for editing hero.sav (EUR / USA or JPN)

**Comment by ghost** [comment]
NO COMMON;QUEST;COTTAGE;EVENT_FLAG;MAP_FLAG;STAGE_FLAG: I ONLY EDited HERO

**Comment by Brionjv** [comment]
The game delete everything if a file in your save file directory is missing, check if all files are in your save file folder, else sent your save file folder to see what goes wrong.

**Comment by ghost** [comment]
I HAVE ALL FILES
