### ISSUE TITLE
Editor will not read .sav files

### ISSUE THREAD

**Issue by erithebat** [Brionjv/Miitopia-Save-Editor#9]
![2019-07-21 (2)](https://user-images.githubusercontent.com/49794546/61590515-88d99500-abb2-11e9-847b-2f9d7326f08b.png)
  

I get this alert trying to open my file, please update the editor.

**Comment by Sakoya0** [comment]
I have this error too ! Please, fix this ! (I use a emulator, this work too, no ?)

**Comment by Brionjv** [comment]
> ![2019-07-21 (2)](https://user-images.githubusercontent.com/49794546/61590515-88d99500-abb2-11e9-847b-2f9d7326f08b.png)
> 
> I get this alert trying to open my file, please update the editor.




> I have this error too ! Please, fix this ! (I use a emulator, this work too, no ?)


You need to have Package.IO.dll file to same folder as Miitopia save editor

**Comment by Sakoya0** [comment]
It works, thank you very much !!! ^^

**Comment by Brionjv** [comment]
no problem
